# Generated by Django 4.0.3 on 2022-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.BigAutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='id',
            field=models.BigAutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.BigAutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
